"""Add sequence rating and approved sequence ID to conversations

Revision ID: 243e8c852ef8
Revises: efbe576fc0a8
Create Date: 2025-08-06 15:08:07.120790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '243e8c852ef8'
down_revision = 'efbe576fc0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_sequence_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('approved_sequence_id')
        batch_op.drop_column('sequence_rating')

    # ### end Alembic commands ###
