"""Add theme preference to users

Revision ID: 24ad33dcc753
Revises: 
Create Date: 2025-07-24 18:01:00.095956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ad33dcc753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('invoices')
    op.drop_table('devis_items')
    op.drop_table('treatment_plans')
    op.drop_table('invoice_items')
    op.drop_table('payments')
    op.drop_table('scheduled_payments')
    op.drop_table('schedule_blocks')
    op.drop_table('payment_plans')
    op.drop_table('patient_education')
    op.drop_table('devis')
    op.drop_table('dental_pricing')
    op.drop_table('patients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    op.create_table('patients',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('emergency_contact', sa.TEXT(), nullable=True),
    sa.Column('insurance_info', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dental_pricing',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tarmed_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description_fr', sa.TEXT(), nullable=False),
    sa.Column('description_de', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('base_price', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarmed_code')
    )
    op.create_table('devis',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('devis_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('validity_date', sa.DATE(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('treatment_plan_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devis_number')
    )
    op.create_table('patient_education',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_plans',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('invoice_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('installments', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_blocks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('block_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_payments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('payment_plan_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tarmed_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_plans',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('plan_data', sa.TEXT(), nullable=False),
    sa.Column('consultation_text', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devis_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('devis_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tarmed_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('paid_amount', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('appointments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('appointment_time', sa.TIME(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('treatment_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('doctor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('room', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('treatment_plan_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
