"""Add Patient model and enhance Conversation with case management

Revision ID: 2855caa2c235
Revises: 77b1785b42a3
Create Date: 2025-07-25 21:05:16.067799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2855caa2c235'
down_revision = '77b1785b42a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create patients table if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'patients' not in inspector.get_table_names():
        op.create_table('patients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('patient_number', sa.String(length=50), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(length=10), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('mobile', sa.String(length=50), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('allergies', sa.Text(), nullable=True),
        sa.Column('medical_notes', sa.Text(), nullable=True),
        sa.Column('insurance_info', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_visit', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'patient_number', name='_user_patient_number_uc')
        )
    
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('case_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_treatment_plan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('treatment_plan_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('case_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chief_complaint', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('teeth_involved', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('procedures_discussed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('insurance_coverage', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_conversations_patient_id', 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_patient_id', type_='foreignkey')
        batch_op.drop_column('insurance_coverage')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('tags')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('procedures_discussed')
        batch_op.drop_column('teeth_involved')
        batch_op.drop_column('chief_complaint')
        batch_op.drop_column('case_summary')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('treatment_plan_approved')
        batch_op.drop_column('has_treatment_plan')
        batch_op.drop_column('case_type')
        batch_op.drop_column('patient_id')
    
    # Drop patients table if it exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'patients' in inspector.get_table_names():
        op.drop_table('patients')
    # ### end Alembic commands ###
