"""Add settings field to User model

Revision ID: 77b1785b42a3
Revises: 24ad33dcc753
Create Date: 2025-07-25 15:31:54.230768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b1785b42a3'
down_revision = '24ad33dcc753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
